[helpers]
get_secret = "bw get password {{0}} --raw"

[default.files]
".zshrc" = "~/.zshrc"
".bashrc" = "~/.bashrc"
".config" = "~/.config"
".justfile" = "~/.justfile"
".vim" = "~/.vim"
".p10k.zsh" = "~/.p10k.zsh"
"binaries" = "~/binaries"
"scripts" = "~/scripts"
"komorebi.json" = "~/komorebi.json"
"komorebi.bar.json" = "~/komorebi.bar.json"

[powershell.files]
"Documents/PowerShell/Microsoft.PowerShell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
