"$schema" = 'https://starship.rs/config-schema.json'

palette = "custom"

format = """
[░▒▓](accent_light)\
$os\
$shell\
$hostname\
[](bg:primary fg:accent_light)\
$directory\
[](fg:primary bg:secondary)\
$git_branch\
$git_status\
[](fg:secondary bg:tertiary)\
$rust\
$golang\
$python\
$lua\
$c\
$nix_shell\
[](fg:tertiary)\
$fill\
[](quaternary)\
$cmd_duration$time\
[▓▒░](quaternary)\
\n$character"""

right_format = ""

[palettes.custom]
accent_light = "#a3aed2"
base_dark = "#090c0c"
primary = "#769ff0"
secondary = "#394260"
tertiary = "#212736"
quaternary = "#1d2230"
text_light = "#e3e5e5"
text_dim = "#a0a9cb"
character = "#cba6f7"

[directory]
style = "fg:text_light bg:primary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[hostname]
style = "bg:accent_light fg:base_dark"

[git_branch]
symbol = ""
style = "bg:secondary"
format = '[[ $symbol $branch ](fg:primary bg:secondary)]($style)'

[git_status]
style = "bg:secondary"
format = '[[($all_status$ahead_behind )](fg:primary bg:secondary)]($style)'

[nodejs]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[rust]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[golang]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[php]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[python]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[lua]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[c]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[dart]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = '[[ $symbol $percentage ](fg:text_dim bg:quaternary)]'

[docker_context]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol $context ](fg:primary bg:tertiary)]($style)'

[package]
symbol = "󰏗"
style = "bg:tertiary"
format = '[[ $symbol $version ](fg:primary bg:tertiary)]($style)'

[nix_shell]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol $state ](fg:primary bg:tertiary)]($style)'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:quaternary"
format = '[[  $time ](fg:text_dim bg:quaternary)]($style)'

[cmd_duration]
min_time = 2_000
show_milliseconds = false
style = "bg:quaternary"
format = '[[ 󱎫 $duration ](fg:yellow bg:quaternary)]($style)'

[character]
success_symbol = "[❯](character)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](yellow)"
vimcmd_visual_symbol = "[❮](red)"
vimcmd_replace_symbol = "[❮](red)"
vimcmd_replace_one_symbol = "[❮](red)"

[os]
disabled = false
style = "bg:accent_light fg:base_dark"
format = "[ $symbol ]($style)"

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = "󰈄"
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰈄"
Gentoo = ""
HardenedBSD = "󰈄"
Illumos = "󰈄"
Kali = ""
Linux = ""
Mabox = "󰈄"
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = "󰈄"
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = ""
openSUSE = ""
OracleLinux = "󰈄"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰈄"
Solus = ""
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"

[shell]
disabled = false
style = "bg:accent_light fg:base_dark"
format = "[](fg:base_dark bg:accent_light)[ $indicator]($style)"
fish_indicator = "󰈺 "
zsh_indicator = "󱆃 "
bash_indicator = " "
nu_indicator = " "
powershell_indicator = " "
unknown_indicator = " "
