"$schema" = 'https://starship.rs/config-schema.json'

palette = "custom"

format = """
[░▒▓](accent_light)\
[  ](bg:accent_light fg:base_dark)\
[](bg:primary fg:accent_light)\
$directory\
[](fg:primary bg:secondary)\
$git_branch\
$git_status\
[](fg:secondary bg:tertiary)\
$nodejs\
$rust\
$golang\
$php\
[](fg:tertiary bg:quaternary)\
$time\
$cmd_duration\
[ ](fg:quaternary)\
\n$character"""

[palettes.custom]
accent_light = "#a3aed2"
base_dark = "#090c0c"
primary = "#769ff0"
secondary = "#394260"
tertiary = "#212736"
quaternary = "#1d2230"
text_light = "#e3e5e5"
text_dim = "#a0a9cb"
character = "#cba6f7"

[directory]
style = "fg:text_light bg:primary"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:secondary"
format = '[[ $symbol $branch ](fg:primary bg:secondary)]($style)'

[git_status]
style = "bg:secondary"
format = '[[($all_status$ahead_behind )](fg:primary bg:secondary)]($style)'

[nodejs]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[rust]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[golang]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[php]
symbol = ""
style = "bg:tertiary"
format = '[[ $symbol ($version) ](fg:primary bg:tertiary)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:quaternary"
format = '[[  $time ](fg:text_dim bg:quaternary)]($style)'

[cmd_duration]
min_time = 2_000
show_milliseconds = false
style = "bg:quaternary"
format = '[[ 󱎫 $duration ](fg:yellow bg:quaternary)]($style)'

[character]
success_symbol = "[❯](character)"
error_symbol = "[❯](red)"
